services:
  magicmirror:
    image: skussmaul/magicmirror-unified
    container_name: magicmirror
    user: 568:568
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2
    networks:
      macvlan_lan:
        ipv4_address: 192.168.xxx.xxx
    volumes:
      - /mnt/apps/configs/magicmirror/config:/opt/magicmirror/config
      - /mnt/apps/configs/magicmirror/modules:/opt/magicmirror/modules
      - /mnt/apps/configs/magicmirror/css:/opt/magicmirror/css
      - /mnt/apps/configs/magicmirror/mmpm:/home/apps/.config/mmpm
    environment:
      - TZ=America/New_York
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "1"
networks:
  macvlan_lan:
    external: true
    name: npm_macvlan_lan
